CREATE TABLE "fridge-stack_content" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "fridge-stack_content_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"category" varchar(256),
	"addedById" varchar(255) NOT NULL,
	"addedAt" timestamp with time zone DEFAULT '2025-04-21T20:14:56.711Z' NOT NULL,
	"updatedAt" timestamp with time zone,
	"expiryDate" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "fridge-stack_post" ALTER COLUMN "createdAt" SET DEFAULT '2025-04-21T20:14:56.711Z';--> statement-breakpoint
ALTER TABLE "fridge-stack_user" ALTER COLUMN "emailVerified" SET DEFAULT '2025-04-21T20:14:56.712Z';--> statement-breakpoint
ALTER TABLE "fridge-stack_content" ADD CONSTRAINT "fridge-stack_content_addedById_fridge-stack_user_id_fk" FOREIGN KEY ("addedById") REFERENCES "public"."fridge-stack_user"("id") ON DELETE no action ON UPDATE no action;