CREATE TABLE "fridge-stack_saved_recipe" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "fridge-stack_saved_recipe_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(256) NOT NULL,
	"description" text NOT NULL,
	"ingredients" json NOT NULL,
	"instructions" json NOT NULL,
	"usesExpiringItems" json,
	"savedById" varchar(255) NOT NULL,
	"savedAt" timestamp with time zone DEFAULT '2025-05-07T09:28:16.312Z' NOT NULL
);
--> statement-breakpoint
ALTER TABLE "fridge-stack_content" ALTER COLUMN "addedAt" SET DEFAULT '2025-05-07T09:28:16.311Z';--> statement-breakpoint
ALTER TABLE "fridge-stack_post" ALTER COLUMN "createdAt" SET DEFAULT '2025-05-07T09:28:16.310Z';--> statement-breakpoint
ALTER TABLE "fridge-stack_user" ALTER COLUMN "emailVerified" SET DEFAULT '2025-05-07T09:28:16.311Z';--> statement-breakpoint
ALTER TABLE "fridge-stack_saved_recipe" ADD CONSTRAINT "fridge-stack_saved_recipe_savedById_fridge-stack_user_id_fk" FOREIGN KEY ("savedById") REFERENCES "public"."fridge-stack_user"("id") ON DELETE no action ON UPDATE no action;